import { createClient } from "@supabase/supabase-js";
import { ArticleGrid } from "@/components/ArticleGrid";
import { Header } from "@/components/Header";
import { SourceFilter } from "@/components/SourceFilter";
import { Article } from "@/lib/types";

async function getArticles(source?: string): Promise<Article[]> {
  const supabase = createClient(
    process.env.SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  let query = supabase
    .from("articles")
    .select(
      "id, url, source_name, source_slug, title, summary, published_at, scraped_at, image_url"
    )
    .not("summary", "is", null)
    .order("scraped_at", { ascending: false })
    .limit(60);

  if (source) {
    query = query.eq("source_slug", source);
  }

  const { data, error } = await query;

  if (error) {
    console.error("Supabase error:", error.message);
    return [];
  }

  return data as Article[];
}

export const revalidate = 1800;

export default async function HomePage({
  searchParams,
}: {
  searchParams: { source?: string };
}) {
  const articles = await getArticles(searchParams.source);

  return (
    <main className="min-h-screen bg-zinc-950 text-zinc-100">
      <Header />
      <div className="max-w-7xl mx-auto px-4 py-8">
        <SourceFilter activeSlug={searchParams.source} />
        <ArticleGrid articles={articles} />
      </div>
      <footer className="border-t border-zinc-900 mt-16 px-4 py-6">
        <div className="max-w-7xl mx-auto">
          <p className="font-mono text-xs text-zinc-700 text-center">
            Updated daily at 06:00 UTC · Summaries generated by Gemini 2.0
            Flash · Sources scraped automatically
          </p>
        </div>
      </footer>
    </main>
  );
}
