import { ArticleGrid } from "@/components/ArticleGrid";
import { Header } from "@/components/Header";
import { SourceFilter } from "@/components/SourceFilter";
import { Article } from "@/lib/types";

async function getArticles(source?: string): Promise<Article[]> {
  const base =
    process.env.NEXT_PUBLIC_BASE_URL ??
    (process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}`
      : "http://localhost:3000");

  const url = source
    ? `${base}/api/articles?source=${encodeURIComponent(source)}`
    : `${base}/api/articles`;

  try {
    const res = await fetch(url, { next: { revalidate: 1800 } });
    if (!res.ok) return [];
    return res.json();
  } catch {
    return [];
  }
}

export default async function HomePage({
  searchParams,
}: {
  searchParams: { source?: string };
}) {
  const articles = await getArticles(searchParams.source);

  return (
    <main className="min-h-screen bg-zinc-950 text-zinc-100">
      <Header />
      <div className="max-w-7xl mx-auto px-4 py-8">
        <SourceFilter activeSlug={searchParams.source} />
        <ArticleGrid articles={articles} />
      </div>
      <footer className="border-t border-zinc-900 mt-16 px-4 py-6">
        <div className="max-w-7xl mx-auto">
          <p className="font-mono text-xs text-zinc-700 text-center">
            Updated daily at 06:00 UTC · Summaries generated by Gemini Flash
            1.5 · Sources scraped automatically
          </p>
        </div>
      </footer>
    </main>
  );
}
