SITE_CONFIGS = [
    {
        "name": "DCiber",
        "slug": "dciber",
        "url": "https://dciber.org/",
        "type": "html",
        "article_list_selector": "article, .post, .entry",
        "article_link_selector": "h2 a, h3 a, .entry-title a",
        "title_selector": "h1.entry-title, h1.post-title, h1",
        "body_selector": ".entry-content, .post-content, article .content",
        "date_selector": "time.entry-date, time[datetime], .post-date",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "TechXplore",
        "slug": "techxplore",
        "url": "https://techxplore.com/",
        "type": "html",
        "article_list_selector": "article.sorted-article, article",
        "article_link_selector": "h2 a, h3 a",
        "title_selector": "h1.article-title, h1",
        "body_selector": "div.article-main p, .article-body p",
        "date_selector": "p.text-uppercase.text-low, time[datetime]",
        "date_attr": "text",
        "max_articles": 3,
    },
    {
        "name": "Dark Reading",
        "slug": "darkreading",
        "url": "https://www.darkreading.com/",
        "type": "html",
        "article_list_selector": ".ListPreview, .article-listing, article",
        "article_link_selector": "a.ListPreview-title, h3 a, h2 a",
        "title_selector": "h1.ContentHeader-title, h1",
        "body_selector": ".article-body-text p, .ContentBody p",
        "date_selector": "time[datetime], .ContentHeader-date",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "The Cradle",
        "slug": "thecradle",
        "url": "https://thecradle.co/",
        "type": "html",
        "article_list_selector": "article, .post-card",
        "article_link_selector": "h2 a, h3 a, .post-card-title a",
        "title_selector": "h1.article-title, h1",
        "body_selector": ".post-content p, .article-body p",
        "date_selector": "time[datetime], .post-date",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "Pepe Escobar",
        "slug": "muckrack-escobar",
        "url": "https://muckrack.com/pepe-escobar/articles",
        "type": "html",
        "article_list_selector": ".MediaItem, li.media-item",
        "article_link_selector": "a.MediaItem-title, h3 a, a[href]:not([href^='#'])",
        "title_selector": "h1",
        "body_selector": "article p, .article-body p, .story-body p",
        "date_selector": "time[datetime]",
        "date_attr": "datetime",
        "max_articles": 2,
        "follow_external": True,
    },
    {
        "name": "Grey Dynamics",
        "slug": "greydynamics",
        "url": "https://greydynamics.com/insights/",
        "type": "html",
        "article_list_selector": "article.post, .insights-item, article",
        "article_link_selector": "h2 a, h3 a, .entry-title a",
        "title_selector": "h1.entry-title, h1",
        "body_selector": ".entry-content p, .post-content p",
        "date_selector": "time[datetime], .entry-date",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "C4ISRNET",
        "slug": "c4isrnet",
        "url": "https://www.c4isrnet.com/",
        "type": "html",
        "article_list_selector": ".ListItem, .story-item, article",
        "article_link_selector": "h3 a, h4 a, .ListItem-title a",
        "title_selector": "h1.ArticleHead-headline, h1",
        "body_selector": ".ArticleBody p, .article-body p",
        "date_selector": "time[data-timestamp], time[datetime]",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "Bellingcat",
        "slug": "bellingcat",
        "url": "https://www.bellingcat.com/",
        "type": "html",
        "article_list_selector": "article, .bc-post-list-item",
        "article_link_selector": "h2 a, h3 a, .bc-post-title a",
        "title_selector": "h1.entry-title, h1",
        "body_selector": ".entry-content p",
        "date_selector": "time[datetime]",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "Securelist",
        "slug": "securelist",
        "url": "https://securelist.com/",
        "type": "html",
        "article_list_selector": ".c-card, article",
        "article_link_selector": "a.c-card__link, h2 a, h3 a",
        "title_selector": "h1.heading-1, h1",
        "body_selector": ".c-wysiwyg p, .entry-content p",
        "date_selector": "time[datetime], .c-date",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "The Record",
        "slug": "therecord",
        "url": "https://therecord.media/",
        "type": "html",
        "article_list_selector": "article, .article-card",
        "article_link_selector": "h3 a, h2 a",
        "title_selector": "h1",
        "body_selector": ".article-content p, .prose p",
        "date_selector": "time[datetime]",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "SentinelOne Labs",
        "slug": "sentinelone-labs",
        "url": "https://www.sentinelone.com/labs/",
        "type": "html",
        "article_list_selector": ".blog-post-card, article",
        "article_link_selector": "a.blog-post-card__link, h2 a, h3 a",
        "title_selector": "h1.blog-post__title, h1",
        "body_selector": ".blog-post__content p, .entry-content p",
        "date_selector": "time[datetime], .blog-post__date",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "SANS ISC",
        "slug": "sans-isc",
        "url": "https://isc.sans.edu/",
        "type": "html",
        "article_list_selector": ".diarySummary, .diary",
        "article_link_selector": "a[href*='/diary/']",
        "title_selector": "h1, .diaryheadline",
        "body_selector": ".diaryText p, .diarytext, #diaryarchiveid p",
        "date_selector": ".diarydate, time[datetime]",
        "date_attr": "text",
        "base_url": "https://isc.sans.edu",
        "max_articles": 3,
    },
    {
        "name": "Check Point Research",
        "slug": "checkpoint-research",
        "url": "https://research.checkpoint.com/",
        "type": "html",
        "article_list_selector": ".post, article, .blog-post",
        "article_link_selector": "h2 a, h3 a, .post-title a",
        "title_selector": "h1.entry-title, h1",
        "body_selector": ".entry-content p, .post-content p",
        "date_selector": "time[datetime], .entry-date",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "Threat Intelligence RSS",
        "slug": "threatintel-rss",
        "url": "https://feeds.feedburner.com/threatintelligence/pvexyqv7v0v",
        "type": "rss",
        "max_articles": 5,
    },
]
