SITE_CONFIGS = [
    {
        "name": "DCiber",
        "slug": "dciber",
        "url": "https://dciber.org/",
        "type": "html",
        "article_list_selector": "article, .post, .type-post",
        "article_link_selector": "h2 a, h3 a, .entry-title a",
        "title_selector": "h1.entry-title, h1.post-title, h1",
        "body_selector": ".entry-content, .post-content",
        "date_selector": "time[datetime], .entry-date, .posted-on time",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        # TechXplore blocks scrapers — using their RSS feed instead
        "name": "TechXplore",
        "slug": "techxplore",
        "url": "https://techxplore.com/rss-feed/",
        "type": "rss",
        "max_articles": 3,
    },
    {
        # Dark Reading blocks scrapers — using their RSS feed instead
        "name": "Dark Reading",
        "slug": "darkreading",
        "url": "https://www.darkreading.com/rss.xml",
        "type": "rss",
        "max_articles": 3,
    },
    {
        "name": "The Cradle",
        "slug": "thecradle",
        "url": "https://thecradle.co/",
        "type": "html",
        "article_list_selector": "article, .post, [class*='article'], [class*='post-card']",
        "article_link_selector": "h1 a, h2 a, h3 a",
        "title_selector": "h1",
        "body_selector": "article p, .entry-content p, .post-content p, main p",
        "date_selector": "time[datetime], [class*='date'], [class*='time']",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        # Muckrack blocks scrapers — skip, hard to scrape and links to external sites
        "name": "Pepe Escobar",
        "slug": "muckrack-escobar",
        "url": "https://www.strategic-culture.su/authors/pepe-escobar/",
        "type": "html",
        "article_list_selector": "article, .post, [class*='article']",
        "article_link_selector": "h2 a, h3 a, [class*='title'] a",
        "title_selector": "h1",
        "body_selector": "article p, .entry-content p, main p",
        "date_selector": "time[datetime], [class*='date']",
        "date_attr": "datetime",
        "max_articles": 2,
    },
    {
        "name": "Grey Dynamics",
        "slug": "greydynamics",
        "url": "https://greydynamics.com/insights/",
        "type": "html",
        "article_list_selector": "article, .post, [class*='insight'], [class*='card']",
        "article_link_selector": "h1 a, h2 a, h3 a, [class*='title'] a",
        "title_selector": "h1",
        "body_selector": "article p, .entry-content p, .post-content p, main p",
        "date_selector": "time[datetime], [class*='date']",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "C4ISRNET",
        "slug": "c4isrnet",
        "url": "https://www.c4isrnet.com/",
        "type": "html",
        "article_list_selector": "[class*='List'], [class*='story'], [class*='article'], article",
        "article_link_selector": "h1 a, h2 a, h3 a, h4 a",
        "title_selector": "h1",
        "body_selector": "[class*='ArticleBody'] p, [class*='article-body'] p, article p",
        "date_selector": "time[datetime], [class*='date'], [class*='timestamp']",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "Bellingcat",
        "slug": "bellingcat",
        "url": "https://www.bellingcat.com/",
        "type": "html",
        "article_list_selector": "article, [class*='post'], [class*='article']",
        "article_link_selector": "h1 a, h2 a, h3 a",
        "title_selector": "h1",
        "body_selector": ".entry-content p, [class*='content'] p, article p",
        "date_selector": "time[datetime]",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "Securelist",
        "slug": "securelist",
        "url": "https://securelist.com/",
        "type": "html",
        "article_list_selector": "[class*='card'], [class*='Card'], article, [class*='post']",
        "article_link_selector": "h1 a, h2 a, h3 a, [class*='title'] a, [class*='link']",
        "title_selector": "h1",
        "body_selector": "[class*='wysiwyg'] p, [class*='content'] p, article p",
        "date_selector": "time[datetime], [class*='date'], [class*='Date']",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "The Record",
        "slug": "therecord",
        "url": "https://therecord.media/",
        "type": "html",
        "article_list_selector": "article, [class*='article'], [class*='post'], [class*='card']",
        "article_link_selector": "h1 a, h2 a, h3 a",
        "title_selector": "h1",
        "body_selector": "article p, [class*='content'] p, [class*='body'] p, main p",
        "date_selector": "time[datetime], [class*='date']",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "SentinelOne Labs",
        "slug": "sentinelone-labs",
        "url": "https://www.sentinelone.com/labs/",
        "type": "html",
        "article_list_selector": "[class*='post'], [class*='card'], [class*='blog'], article",
        "article_link_selector": "h1 a, h2 a, h3 a, [class*='title'] a",
        "title_selector": "h1",
        "body_selector": "[class*='content'] p, [class*='body'] p, article p, main p",
        "date_selector": "time[datetime], [class*='date'], [class*='Date']",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "SANS ISC",
        "slug": "sans-isc",
        "url": "https://isc.sans.edu/diary.html",
        "type": "html",
        "article_list_selector": ".diarySummary, [class*='diary'], .diaryentry",
        "article_link_selector": "a[href*='/diary/']",
        "title_selector": "h1, .diarytitle, [class*='diary-title']",
        "body_selector": ".diaryText, [class*='diarytext'], [class*='diary-text'], .diaryentry p",
        "date_selector": ".diarydate, [class*='diarydate'], time[datetime]",
        "date_attr": "text",
        "base_url": "https://isc.sans.edu",
        "max_articles": 3,
    },
    {
        "name": "Check Point Research",
        "slug": "checkpoint-research",
        "url": "https://research.checkpoint.com/",
        "type": "html",
        "article_list_selector": "article, .post, [class*='post'], [class*='article']",
        "article_link_selector": "h1 a, h2 a, h3 a, [class*='title'] a",
        "title_selector": "h1",
        "body_selector": ".entry-content p, [class*='content'] p, article p",
        "date_selector": "time[datetime], [class*='date'], .entry-date",
        "date_attr": "datetime",
        "max_articles": 3,
    },
    {
        "name": "Threat Intelligence RSS",
        "slug": "threatintel-rss",
        "url": "https://feeds.feedburner.com/threatintelligence/pvexyqv7v0v",
        "type": "rss",
        "max_articles": 5,
    },
]
